### ISSUE TITLE
Thoth Analysis Fails

### ISSUE THREAD

**Issue by mamurak** [openshift-labs/learn-katacoda#1075]
**In what katacoda scenario did this bug occur?**
Thoth S2I build with Advise on OpenShift

**At what step of the scenario did this happen?**
Building s2i with Thoth Advise

**Describe the bug**
Building the sample app does not produce the "Recommended Stack Report" as indicated in the scenario. The build log reveals that the Thoth stack analysis fails.

**Logs or error messages**
Logs of build step 8:
```
STEP 8: RUN /usr/libexec/s2i/assemble
/tmp/src ~
2021-04-07 13:17:33,485 [413] DEBUG    thamos: Debug mode turned on
2021-04-07 13:17:33,486 [413] DEBUG    thamos: Thamos version: '1.13.0'
2021-04-07 13:17:33,487 [413] ERROR    thamos.config: Schema validation failed: please make sure you run Thamos which supports the supplied configuration file
2021-04-07 13:17:33,490 [413] CRITICAL root: Traceback (most recent call last):
  File "/opt/app-root/bin/thamos", line 8, in <module>
    sys.exit(cli())
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/thamos/cli.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/thamos/cli.py", line 899, in check
    result = configuration.check(runtime_environment_name=runtime_environment)
  File "/opt/app-root/lib/python3.6/site-packages/thamos/config.py", line 563, in check
    self.check_schema()
  File "/opt/app-root/lib/python3.6/site-packages/thamos/config.py", line 600, in check_schema
    validate(instance=self.content, schema=_CONFIG_SCHEMA)
  File "/opt/app-root/lib/python3.6/site-packages/thamos/config.py", line 168, in content
    self.load_config()
  File "/opt/app-root/lib/python3.6/site-packages/thamos/config.py", line 232, in load_config
    with workdir(config.CONFIG_NAME):
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/app-root/lib/python3.6/site-packages/thamos/utils.py", line 53, in workdir
    f"No {file_lookup} found in the current directory {os.getcwd()!r} or in any of its parent "
thamos.exceptions.NoProjectDirError: No .thoth.yaml found in the current directory '/tmp/src' or in any of its parent directories, you can generate it using '/opt/app-root/bin/thamos config'

>>> Check of the configuration file failed, proceeding with the installation process based on the error fallback flag
>>> Thoth s2i builder image version: 0.26.0
>>> Performing hardware and software discovery...
2021-04-07 13:17:35,089 [417] DEBUG    thamos: Debug mode turned on
2021-04-07 13:17:35,090 [417] DEBUG    thamos: Thamos version: '1.13.0'
2021-04-07 13:17:35,092 [417] INFO     thamos: Creating configuration file from a configuration template 'thoth_conf_template.yaml'
2021-04-07 13:17:35,092 [417] DEBUG    thamos.config: Reading configuration from 'thoth_conf_template.yaml'
2021-04-07 13:17:35,093 [417] INFO     thamos.config: Discovering host runtime environment
2021-04-07 13:17:35,094 [417] INFO     thamos.discover: Detected CPU: cpu_family: 6, cpu_model: 79, cpu_model_name: Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz
2021-04-07 13:17:35,101 [417] INFO     thamos.discover: No CUDA version detected
2021-04-07 13:17:35,101 [417] DEBUG    thamos.discover: Unable to detect CUDA version - nvcc returned non-zero version: {'stdout': '', 'stderr': '/bin/sh: nvcc: command not found\n', 'return_code': 127, 'command': 'nvcc --version', 'timeout': 60, 'message': '<thoth.analyzer.command.CommandResult object at 0x7f62c9100438>'}
2021-04-07 13:17:35,117 [417] INFO     thamos.discover: Detected Thoth s2i tooling 'quay.io/thoth-station/s2i-thoth-ubi8-py36:v0.26.0'
2021-04-07 13:17:35,118 [417] DEBUG    thamos.config: Writing configuration file to '/tmp/src/.thoth.yaml'
>>> Thoth's configuration file after hardware and software discovery:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'yaml'

>>> Asking Thoth for advise...
2021-04-07 13:17:36,800 [426] DEBUG    thamos: Debug mode turned on
2021-04-07 13:17:36,800 [426] DEBUG    thamos: Thamos version: '1.13.0'
2021-04-07 13:17:36,803 [426] INFO     thamos.config: Expanding configuration file based on environment variables
2021-04-07 13:17:36,806 [426] WARNING  thamos: Development dependencies will not be considered during the resolution process - see https://thoth-station.ninja/j/no_dev
2021-04-07 13:17:36,806 [426] INFO     thamos.lib: Using Pipenv files to manage dependencies located in '/tmp/src'
2021-04-07 13:17:36,806 [426] INFO     thamos.lib: Submitting Pipfile.lock as a base for user's stack scoring - see https://thoth-station.ninja/j/user_stack
2021-04-07 13:17:36,809 [426] CRITICAL root: Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/thoth/python/project.py", line 79, in from_files
    pipfile = Pipfile.from_file(pipfile_path)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/python/pipfile.py", line 393, in from_file
    return cls.from_string(pipfile_file.read())
  File "/opt/app-root/lib/python3.6/site-packages/thoth/python/pipfile.py", line 408, in from_string
    return cls.from_dict(parsed)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/python/pipfile.py", line 416, in from_dict
    thoth_section = ThothPipfileSection.from_dict(dict_.pop("thoth", {}))
  File "/opt/app-root/lib/python3.6/site-packages/thoth/python/pipfile.py", line 329, in from_dict
    allow_prereleases = dict_.pop("allow_prereleases") or {}
KeyError: 'allow_prereleases'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/bin/thamos", line 8, in <module>
    sys.exit(cli())
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/thamos/cli.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/thamos/cli.py", line 534, in advise
    no_user_stack=no_user_stack,
  File "/opt/app-root/lib/python3.6/site-packages/thamos/lib.py", line 537, in advise_here
    without_pipfile_lock=not os.path.exists("Pipfile.lock")
  File "/opt/app-root/lib/python3.6/site-packages/thoth/python/project.py", line 83, in from_files
    ) from exc
thoth.python.exceptions.FileLoadError: Failed to load Pipfile (path: /tmp/src: 'allow_prereleases'

>>> Thoth stack analysis failed with the following log:
2021-04-07 13:17:38,468 [430] DEBUG    thamos: Debug mode turned on
2021-04-07 13:17:38,469 [430] DEBUG    thamos: Thamos version: '1.13.0'
2021-04-07 13:17:38,470 [430] INFO     thamos.config: Expanding configuration file based on environment variables
2021-04-07 13:17:38,474 [430] WARNING  thamos.config: TLS verification turned off, its highly recommended to use a secured connection, see configuration file for configuration options
2021-04-07 13:17:39,150 [430] DEBUG    thamos.lib: Using API: https://api.moc.thoth-station.ninja/api/v1
2021-04-07 13:17:39,159 [430] CRITICAL root: Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/thamos/lib.py", line 210, in _get_last_analysis_id
    with open(LAST_ANALYSIS_ID_FILE, "r") as analysis_id_file:
FileNotFoundError: [Errno 2] No such file or directory: '.thoth_last_analysis_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/bin/thamos", line 8, in <module>
    sys.exit(cli())
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/thamos/cli.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/thamos/cli.py", line 705, in log
    log_str = get_log()
  File "/opt/app-root/lib/python3.6/site-packages/thamos/lib.py", line 104, in wrapper
    result = func(api_client, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/thamos/lib.py", line 776, in get_log
    analysis_id = _get_last_analysis_id()
  File "/opt/app-root/lib/python3.6/site-packages/thamos/lib.py", line 215, in _get_last_analysis_id
    ) from exc
FileNotFoundError: Cannot retrieve last analysis id, you need to provide analysis id explicitly

>>> Restoring previous requirements lock
>>> Thoth advises are not activated
~
---> Installing application source ...
2021-04-07 13:17:41,161 [454] DEBUG    thamos: Debug mode turned on
2021-04-07 13:17:41,162 [454] DEBUG    thamos: Thamos version: '1.13.0'
2021-04-07 13:17:41,164 [454] INFO     thamos.config: Expanding configuration file based on environment variables
2021-04-07 13:17:41,167 [454] WARNING  thamos.lib: Development dependencies will not be installed - see https://thoth-station.ninja/j/no_dev
2021-04-07 13:17:41,167 [454] INFO     thamos.lib: Using 'pipenv' installation method to install dependencies stated in '/opt/app-root/src'
---------------------------------- Pipfile.lock ----------------------------------
{
    "_meta": {
        "hash": {
            "sha256": "2f354eaddecf43134b8d5a1609be109224aa91a1bfa02eb661d752046ed64bac"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi-org",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "daiquiri": {
            "hashes": [
                "sha256:0d5bf9c5719fbca4928dc2a882c165cd2b5c81be28f7f1626ced04c1c6b4aae2",
                "sha256:236183ba51f35f4ae0e23fd20119d0fa082995c08d77bd562dbc00ea8f504bf6"
            ],
            "index": "pypi-org",
            "version": "==2.1.1"
        },
        "python-json-logger": {
            "hashes": [
                "sha256:b7a31162f2a01965a5efb94453ce69230ed208468b0bbc7fdfc56e6d8df2e281"
            ],
            "version": "==0.1.11"
        }
    },
    "develop": {}
}
---------------------------------- Pipfile.lock ----------------------------------
2021-04-07 13:17:41,169 [454] INFO     micropipenv: Installing 'daiquiri'
Collecting daiquiri==2.1.1
  Downloading daiquiri-2.1.1-py2.py3-none-any.whl (17 kB)
Installing collected packages: daiquiri
  Attempting uninstall: daiquiri
    Found existing installation: daiquiri 3.0.0
    Uninstalling daiquiri-3.0.0:
      Successfully uninstalled daiquiri-3.0.0
Successfully installed daiquiri-2.1.1
2021-04-07 13:17:42,028 [454] INFO     micropipenv: Installing 'python-json-logger'
Collecting python-json-logger==0.1.11
  Downloading python-json-logger-0.1.11.tar.gz (6.0 kB)
Building wheels for collected packages: python-json-logger
  Building wheel for python-json-logger (setup.py): started
  Building wheel for python-json-logger (setup.py): finished with status 'done'
  Created wheel for python-json-logger: filename=python_json_logger-0.1.11-py2.py3-none-any.whl size=4204 sha256=dd0ba668ef0f748038ac29ab58dd6d07b3f9213fb9a99f1a5fbdaf734538b62c
  Stored in directory: /tmp/pip-ephem-wheel-cache-5jjg6r5r/wheels/99/ad/da/22b0dbe95e769350f2641f2f18c25d3ba3a0ce21dd1f655cf1
Successfully built python-json-logger
Installing collected packages: python-json-logger
  Attempting uninstall: python-json-logger
    Found existing installation: python-json-logger 2.0.1
    Uninstalling python-json-logger-2.0.1:
      Successfully uninstalled python-json-logger-2.0.1
Successfully installed python-json-logger-0.1.11
```

**Comment by blues-man** [comment]
This is actually an old issue solved with Thoth 1.18
