### ISSUE TITLE
Testing with Arquillian Cube, Step 2 of 3, mvn failed

### ISSUE THREAD

**Issue by briansutelus** [openshift-labs/learn-katacoda#1111]
https://learn.openshift.com/middleware/courses/middleware-spring-boot/arquillian-cube

```
mvn clean package -Popenshift

...
-> Trying internal type for name:Pod
-> [INFO] F8: Waiting for build fruit-s2i-2 to complete...
-> [INFO] F8: pulling image error : open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: no such file or directory
-> [INFO] F8: error: build error: unable to get registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.3
-> Trying internal type for name:Build
-> [ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
-> [INFO] ------------------------------------------------------------------------
-> [INFO] BUILD FAILURE
-> [INFO] ------------------------------------------------------------------------
-> [INFO] Total time: 36.112 s
-> [INFO] Finished at: 2021-05-08T16:29:57+00:00
-> [INFO] Final Memory: 58M/739M
-> [INFO] ------------------------------------------------------------------------
-> [WARNING] Ignoring error for already closed/closing connection
-> [ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.40:build (default-cli) on project fruit: Failed to execute the build: Unable to build the image using the OpenShift build service: OpenShift Build fruit-s2i-2 error: Failed: PullBuilderImageFailed -> [Help 1]
-> [ERROR] 
-> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
-> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
-> [ERROR] 
-> [ERROR] For more information about the errors and possible solutions, please read the following articles:
-> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
May 08, 2021 4:29:57 PM org.jboss.shrinkwrap.resolver.impl.maven.embedded.BuildTrigger build
SEVERE: Maven build failed - the exit code is: 1
=================================================================
===   Embedded Maven build stopped: arquillian-cube/pom.xml   ===
=================================================================
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.example:fruit:jar:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ line 115, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building rhoar-training 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ fruit ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ fruit ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ fruit ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ fruit ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ fruit ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ fruit ---
[INFO] Building jar: /root/projects/rhoar-getting-started/spring/arquillian-cube/target/fruit-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- fabric8-maven-plugin:3.5.40:build (default-cli) @ fruit ---
[INFO] F8: Using OpenShift build with strategy S2I
[INFO] F8: Running generator spring-boot
[INFO] F8: spring-boot: Using Docker image registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.3 as base / builder
[INFO] Copying files to /root/projects/rhoar-getting-started/spring/arquillian-cube/target/docker/fruit/latest/build/maven
[INFO] Building tar: /root/projects/rhoar-getting-started/spring/arquillian-cube/target/docker/fruit/latest/tmp/docker-build.tar
[INFO] F8: [fruit:latest] "spring-boot": Created docker source tar /root/projects/rhoar-getting-started/spring/arquillian-cube/target/docker/fruit/latest/tmp/docker-build.tar
[INFO] F8: Using BuildServiceConfig fruit-s2i for Source strategy
[INFO] F8: Adding to ImageStream fruit
[INFO] F8: Starting Build fruit-s2i
Trying internal type for name:Pod
[INFO] F8: Waiting for build fruit-s2i-2 to complete...
[INFO] F8: pulling image error : open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: no such file or directory
[INFO] F8: error: build error: unable to get registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.3
Trying internal type for name:Build
[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 36.112 s
[INFO] Finished at: 2021-05-08T16:29:57+00:00
[INFO] Final Memory: 58M/739M
[INFO] ------------------------------------------------------------------------
[WARNING] Ignoring error for already closed/closing connection
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.40:build (default-cli) on project fruit: Failed to execute the build: Unable to build the image using the OpenShift build service: OpenShift Build fruit-s2i-2 error: Failed: PullBuilderImageFailed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 40.315 sec <<< FAILURE!
com.example.FruitControllerIntTest  Time elapsed: 40.313 sec  <<< ERROR!
java.lang.IllegalStateException: Maven build has failed, see logs for details
        at org.fabric8.maven.plugin.build.Fabric8MavenPluginResourceGeneratorBuilder.build(Fabric8MavenPluginResourceGeneratorBuilder.java:131)
        at org.arquillian.cube.kubernetes.impl.SessionManager.start(SessionManager.java:212)
        at org.arquillian.cube.kubernetes.impl.SessionManagerLifecycle.start(SessionManagerLifecycle.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
        at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
        at org.arquillian.cube.kubernetes.impl.SuiteListener.start(SuiteListener.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
        at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
        at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:71)
        at org.jboss.arquillian.junit.AdaptorManager.initializeAdaptor(AdaptorManager.java:23)
        at org.jboss.arquillian.junit.AdaptorManagerWithNotifier.initializeAdaptor(AdaptorManagerWithNotifier.java:19)
        at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:109)
        at org.arquillian.cube.requirement.ArquillianConditionalRunner.run(ArquillianConditionalRunner.java:28)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error: 
  com.example.FruitControllerIntTest: Maven build has failed, see logs for details

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.129 s
[INFO] Finished at: 2021-05-08T16:29:58+00:00
[INFO] Final Memory: 35M/286M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project fruit: There are test failures.
[ERROR] 
[ERROR] Please refer to /root/projects/rhoar-getting-started/spring/arquillian-cube/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by jamesfalkner** [comment]
Scenario has been removed in favor more modern testing (e.g. with Spring testing framework) and lack of activity in the upstream project (last release 3+ years ago).
