### ISSUE TITLE
Exercises not starting up on Chrome Web Browser

### ISSUE THREAD

**Issue by Zografska** [openshift-labs/learn-katacoda#1339]
This occured when i try to start any exercise, the window is frozen.

Name the katacoda you were using - https://www.katacoda.com/courses/git/10

**At what step of the scenario did this happen?** - On opening the scenario. After clicking on the "Start Scenario" button.

If you can't remember the exact step, try to explain where in the scenario did the bug happen

**Describe the bug**
The page is unresponsive, nothing is clickable. The terminal is not started up.

A clear and concise description of what the bug is

Paste in any error message you got
jquery-3.5.1.min.js:2 Uncaught ReferenceError: trackJs is not defined
    at TerminalViewLayout.init.init (terminal-application.js?v=20211119:1:1261)
    at window.on_page_load (10:497:17)
    at App.init (application.js?v=20211119:1:162264)
    at HTMLDocument.<anonymous> (10:835:13)
    at e (jquery-3.5.1.min.js:2:30005)
    at t (jquery-3.5.1.min.js:2:30307)

**Screenshots**
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/51208187/161424129-b86dab7f-2ef1-4371-a5f3-026195ae2e83.png">

**Comment by lepazca** [comment]
Hi, I have the same issue with Docker course, unresponsive terminal.

![Screenshot_20220406_205428](https://user-images.githubusercontent.com/17462646/162098757-3753d362-0357-4b4e-b948-4a34c6b01771.png)

Edit: I have tried with Chrome too, the pic is from Mozilla.

**Comment by dadav** [comment]
I have the same error with firefox 98.0.2
