### ISSUE TITLE
The Training portal freezes

### ISSUE THREAD

**Issue by dineshgpillai** [openshift-labs/learn-katacoda#351]
Hi 

I am unable to launch anything within your training portal. Screen freezes

**Comment by BenHall** [comment]
Sorry for the problems. Could you tell us what freezes? If you could send us a screenshot that woudl be helpful to help us identify the issue.

**Comment by dineshgpillai** [comment]
When I launch any Scenario from the learning portal and click on Start Scenario; it just freezes and does nothing. I have attached an example
![screenshot 2019-02-04 at 13 57 56](https://user-images.githubusercontent.com/25434392/52212738-251e1280-2885-11e9-8976-26efeca38c3f.png)

**Comment by dineshgpillai** [comment]
https://learn.openshift.com/introduction/

**Comment by BenHall** [comment]
Thanks! Do you have any Javascript errors in the developer console?

**Comment by dineshgpillai** [comment]
Yes I will send you that as well...

**Comment by dineshgpillai** [comment]
application.js:1 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at getCookie (https://katacoda.com/js/application.js:1:131404)
    at TerminalViewLayout.init (https://katacoda.com/javascripts/terminal-application.js:1:1067)
    at window.on_page_load (https://katacoda.com/embed/openshift/courses/introduction/getting-started/?embed=true&ui=inline&host=learn.openshift.com&url=https%3A%2F%2Flearn.openshift.com%2Fintroduction%2Fgetting-started%2F&target=katacoda-scenario-1&color=1a1a1a&secondary=cc0000&font=Open%20Sans&fontheader=Open%20Sans&ctaurl=https%3A%2F%2Flearn.openshift.com%2Fintroduction&ctatext=More%20Scenarios&code=:504:17)
    at App.init (https://katacoda.com/js/application.js:1:133133)
    at HTMLDocument.<anonymous> (https://katacoda.com/embed/openshift/courses/introduction/getting-started/?embed=true&ui=inline&host=learn.openshift.com&url=https%3A%2F%2Flearn.openshift.com%2Fintroduction%2Fgetting-started%2F&target=katacoda-scenario-1&color=1a1a1a&secondary=cc0000&font=Open%20Sans&fontheader=Open%20Sans&ctaurl=https%3A%2F%2Flearn.openshift.com%2Fintroduction&ctatext=More%20Scenarios&code=:550:13)
    at j (https://katacoda.com/js/jquery-2.1.1.min.js:2:26860)
    at Object.fireWith [as resolveWith] (https://katacoda.com/js/jquery-2.1.1.min.js:2:27673)
    at Function.ready (https://katacoda.com/js/jquery-2.1.1.min.js:2:29467)
    at HTMLDocument.I (https://katacoda.com/js/jquery-2.1.1.min.js:2:29658)

**Comment by BenHall** [comment]
Thanks! Very helpful. We'll investigate and be in touch.

**Comment by dineshgpillai** [comment]
Thank you Ben

**Comment by BenHall** [comment]
@dineshgpillai Could you please try again?

**Comment by dineshgpillai** [comment]
I just tried it; same problem Ben

**Comment by BenHall** [comment]
Please ensure you have cleared any local caches of the Javascript.

**Comment by dineshgpillai** [comment]
ok will clear and try again

**Comment by BenHall** [comment]
Great! thanks
