### ISSUE TITLE
Swagger not coming up in first step

### ISSUE THREAD

**Issue by jarcher** [openshift-labs/learn-katacoda#757]
On the first step in the intro to Kogito  - after running the mvn clean compile quarkus:dev

I see this below with a JRE error message and the swagger interface does not come up

Downloaded from central: https://repo.maven.apache.org/maven2/org/freemarker/freemarker/2.3.29/freemarker-2.3.29.jar (1.6 MB at 2.2 MB/s)
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.UnsupportedClassVersionError: org/kie/kogito/quarkus/deployment/ProcessCompilationProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:52)
Caused by: java.lang.RuntimeException: java.lang.UnsupportedClassVersionError: org/kie/kogito/quarkus/deployment/ProcessCompilationProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:112)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:47)
Caused by: java.lang.UnsupportedClassVersionError: org/kie/kogito/quarkus/deployment/ProcessCompilationProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:285)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:251)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at io.quarkus.dev.IsolatedDevModeMain.setupRuntimeCompilation(IsolatedDevModeMain.java:119)
        at io.quarkus.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:231)
        at io.quarkus.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:39)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:131)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:84)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:108)
        ... 1 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.281 s
[INFO] Finished at: 2020-05-07T11:44:56Z
[INFO] ------------------------------------------------------------------------
$ ^C
$

**Comment by jarcher** [comment]
working now
