### ISSUE TITLE
The Eclipse Vert.x Development Scenarios are failing

### ISSUE THREAD

**Issue by kidswain** [openshift-labs/learn-katacoda#761]
They appear to be sensitive to the fixed version of infinispan.
Specifically:
[MicroTrader App Part 1: Quote Genertor](https://learn.openshift.com/middleware/courses/middleware-vertx/getting-started-vertx)
[MicroTrader App Part 2: Portfolio Service](https://learn.openshift.com/middleware/courses/middleware-vertx/portfolio-service)
[MicroTrader App Part 3: Compulsive Traders](https://learn.openshift.com/middleware/courses/middleware-vertx/compulsive-traders)
[MicroTrader App Part 4: Audit Service](https://learn.openshift.com/middleware/courses/middleware-vertx/audit-service)

**Comment by blues-man** [comment]
Right, from `quote-generator` Pod log:

```

WARNING: Cannot find Infinispan config 'infinispan.xml', using default
--
  | May 12, 2020 8:56:31 AM io.vertx.core.impl.VertxImpl
  | SEVERE: Failed to join cluster
  | org.infinispan.commons.CacheConfigurationException: ISPN000327: Cannot find a parser for element 'infinispan' in namespace 'urn:infinispan:config:9.4'. Check that your configuration is up-to date for this version of Infinispan.
  | at org.infinispan.configuration.parsing.ParserRegistry.parseElement(ParserRegistry.java:174)
  | at org.infinispan.configuration.parsing.ParserRegistry.parse(ParserRegistry.java:150)
  | at org.infinispan.configuration.parsing.ParserRegistry.parse(ParserRegistry.java:137)
  | at org.infinispan.configuration.parsing.ParserRegistry.parse(ParserRegistry.java:123)
  | at io.vertx.ext.cluster.infinispan.InfinispanClusterManager.lambda$join$8(InfinispanClusterManager.java:228)
  | at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)


```

**Comment by kidswain** [comment]
It’s happening in all modules in all scenarios.
Changing the infinispan version in the pom.xml to the current stable version appears to fix the problem.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by blues-man** [comment]
I'm trying with latest GA I see on Red Hat maven repo for infinispan-cloud `9.4.19.Final` and looks working on `quote-generator`, but not in `microtrader-dashboard. Did you tried any specific version that you saw working in all Steps in Scenarios?
Thanks!

**Comment by kidswain** [comment]
NP, happy to help.
I used version 10.1.7.Final from the Infinispan<https://infinispan.org/> Homepage.
That appeared to work, although I was unable to restart the code safely.

Joseph de Graft-Johnson
jdgj@hotmail.co.uk<mailto:jdgj@hotmail.co.uk>
mobile: +44 (0)77 9693 7284

**Comment by btannous** [comment]
I think this might be resolved with this PR <once merged in> https://github.com/openshift-katacoda/rhoar-getting-started/pull/35

**Comment by kidswain** [comment]
I'm not seeing this error in the MicroTrader Part 1: Quote Generator Scenario.
