### ISSUE TITLE
Micro-Trader-Dashboard Pod never starts successfully

### ISSUE THREAD

**Issue by kidswain** [openshift-labs/learn-katacoda#775]
IN the MicroTrader Part 1: Quote Generator Scenario, the Micro-Trader-Dashboard never renders.
Following error is reported in the Log file:
SEVERE: Unhandled exception
java.lang.NoSuchMethodError: io.vertx.ext.web.handler.sockjs.PermittedOptions.setAddress(Ljava/lang/String;)Lio/vertx/ext/web/handler/sockjs/PermittedOptions;
	at in.yunyul.vertx.console.circuitbreakers.CircuitBreakersHandler.<init>(CircuitBreakersHandler.java:21)
	at in.yunyul.vertx.console.circuitbreakers.CircuitBreakersConsolePage.mount(CircuitBreakersConsolePage.java:37)
	at in.yunyul.vertx.console.base.WebConsoleRegistry.mount(WebConsoleRegistry.java:92)
	at io.vertx.workshop.dashboard.DashboardVerticle.lambda$start$1(DashboardVerticle.java:67)
	at io.vertx.servicediscovery.impl.DiscoveryImpl.lambda$initialize$1(DiscoveryImpl.java:99)
	at io.vertx.core.impl.CompositeFutureImpl.lambda$join$4(CompositeFutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:126)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:133)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:94)
	at io.vertx.servicediscovery.kubernetes.KubernetesServiceImporter.lambda$start$3(KubernetesServiceImporter.java:142)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:126)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:87)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:152)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:19)
	at io.vertx.core.impl.CompositeFutureImpl.lambda$all$1(CompositeFutureImpl.java:49)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:126)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:87)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:152)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:19)
	at io.vertx.servicediscovery.kubernetes.KubernetesServiceImporter.lambda$publishRecord$9(KubernetesServiceImporter.java:301)
	at io.vertx.servicediscovery.impl.DiscoveryImpl.lambda$publish$6(DiscoveryImpl.java:320)
	at io.vertx.servicediscovery.impl.DefaultServiceDiscoveryBackend.lambda$null$0(DefaultServiceDiscoveryBackend.java:74)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:126)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:87)
	at io.vertx.core.Future.lambda$map$3(Future.java:353)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:126)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:87)
	at io.vertx.ext.cluster.infinispan.impl.InfinispanAsyncMapImpl.lambda$null$1(InfinispanAsyncMapImpl.java:64)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by blues-man** [comment]
Hi @kidswain thanks for reporting this. I was working on it from the previous issue #761 where I updated all infinispan-cloud to latest [GA](https://maven.repository.redhat.com/ga/org/infinispan/infinispan-cloud/) and opened this issue on the lab repo [here](https://github.com/openshift-katacoda/rhoar-getting-started/issues/33)
