### ISSUE TITLE
Error in Serverless Camel K scenario

### ISSUE THREAD

**Issue by sobkowiak** [openshift-labs/learn-katacoda#953]
**In what katacoda scenario did this bug occur?**
Serverless Camel K

**At what step of the scenario did this happen?**
Step 2: Running the API integration

**Describe the bug**
After creating integration with command

```
kamel run --name api helper/MinioCustomizer.java camel-api/API.java --property-file camel-api/minio.properties --open-api helper/openapi.yaml -d camel-openapi-java
```
the integration is built but the pod fails with error

```
[1] Monitoring pod api-69cd66496f-xdvnn
[1] exec java -cp ./resources:/etc/camel/conf:/etc/camel/conf.d:/etc/camel/resources:/etc/camel/sources/i-source-000:/etc/camel/sources/i-source-001:/etc/camel/sources/i-source-002:dependencies/camel-k-integration-1.2.0-runner.jar:dependencies/com.amazonaws.aws-java-sdk-core-1.11.714.jar:dependencies/com.amazonaws.aws-java-sdk-kms-1.11.714.jar:dependencies/com.amazonaws.aws-java-sdk-s3-1.11.714.jar:dependencies/com.amazonaws.jmespath-java-1.11.714.jar:dependencies/com.fasterxml.jackson.core.jackson-annotations-2.11.2.jar:dependencies/com.fasterxml.jackson.core.jackson-core-2.11.2.jar:dependencies/com.fasterxml.jackson.core.jackson-databind-2.11.2.jar:dependencies/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.11.2.jar:dependencies/com.fasterxml.jackson.dataformat.jackson-dataformat-xml-2.10.5.jar:dependencies/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.11.2.jar:dependencies/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.11.2.jar:dependencies/com.fasterxml.jackson.datatype.jackson-datatype-joda-2.11.2.jar:dependencies/com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.11.2.jar:dependencies/com.fasterxml.jackson.jaxrs.jackson-jaxrs-base-2.11.2.jar:dependencies/com.fasterxml.jackson.jaxrs.jackson-jaxrs-json-provider-2.11.2.jar:dependencies/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.11.2.jar:dependencies/com.fasterxml.jackson.module.jackson-module-parameter-names-2.11.2.jar:dependencies/com.fasterxml.woodstox.woodstox-core-6.1.1.jar:dependencies/com.sun.activation.jakarta.activation-1.2.1.jar:dependencies/com.sun.istack.istack-commons-runtime-3.0.10.jar:dependencies/commons-codec.commons-codec-1.14.jar:dependencies/io.apicurio.apicurio-data-models-1.0.16.Final.jar:dependencies/io.netty.netty-buffer-4.1.49.Final.jar:dependencies/io.netty.netty-codec-4.1.49.Final.jar:dependencies/io.netty.netty-codec-dns-4.1.49.Final.jar:dependencies/io.netty.netty-codec-http-4.1.49.Final.jar:dependencies/io.netty.netty-codec-http2-4.1.49.Final.jar:dependencies/io.netty.netty-codec-socks-4.1.49.Final.jar:dependencies/io.netty.netty-common-4.1.49.Final.jar:dependencies/io.netty.netty-handler-4.1.49.Final.jar:dependencies/io.netty.netty-handler-proxy-4.1.49.Final.jar:dependencies/io.netty.netty-resolver-4.1.49.Final.jar:dependencies/io.netty.netty-resolver-dns-4.1.49.Final.jar:dependencies/io.netty.netty-transport-4.1.49.Final.jar:dependencies/io.quarkus.arc.arc-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-arc-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-bootstrap-runner-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-core-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-development-mode-spi-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-ide-launcher-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-jackson-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-jaxb-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-mutiny-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-netty-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-security-runtime-spi-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-smallrye-context-propagation-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-vertx-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-vertx-core-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-vertx-http-1.8.0.Final.jar:dependencies/io.quarkus.quarkus-vertx-web-1.8.0.Final.jar:dependencies/io.quarkus.security.quarkus-security-1.1.2.Final.jar:dependencies/io.reactivex.rxjava2.rxjava-2.2.19.jar:dependencies/io.smallrye.common.smallrye-common-annotation-1.3.0.jar:dependencies/io.smallrye.common.smallrye-common-constraint-1.1.0.jar:dependencies/io.smallrye.common.smallrye-common-expression-1.1.0.jar:dependencies/io.smallrye.common.smallrye-common-function-1.1.0.jar:dependencies/io.smallrye.config.smallrye-config-1.8.6.jar:dependencies/io.smallrye.config.smallrye-config-common-1.8.6.jar:dependencies/io.smallrye.reactive.mutiny-0.7.0.jar:dependencies/io.smallrye.reactive.mutiny-context-propagation-0.7.0.jar:dependencies/io.smallrye.reactive.mutiny-reactive-streams-operators-0.7.0.jar:dependencies/io.smallrye.reactive.smallrye-axle-core-1.1.0.jar:dependencies/io.smallrye.reactive.smallrye-axle-generator-1.1.0.jar:dependencies/io.smallrye.reactive.smallrye-mutiny-vertx-core-1.1.0.jar:dependencies/io.smallrye.reactive.smallrye-mutiny-vertx-runtime-1.1.0.jar:dependencies/io.smallrye.reactive.vertx-mutiny-generator-1.1.0.jar:dependencies/io.smallrye.smallrye-context-propagation-1.0.13.jar:dependencies/io.smallrye.smallrye-context-propagation-api-1.0.13.jar:dependencies/io.vertx.vertx-auth-common-3.9.2.jar:dependencies/io.vertx.vertx-bridge-common-3.9.2.jar:dependencies/io.vertx.vertx-codegen-3.9.2.jar:dependencies/io.vertx.vertx-core-3.9.2.jar:dependencies/io.vertx.vertx-rx-gen-3.9.2.jar:dependencies/io.vertx.vertx-rx-java2-3.9.2.jar:dependencies/io.vertx.vertx-web-3.9.2.jar:dependencies/io.vertx.vertx-web-common-3.9.2.jar:dependencies/jakarta.activation.jakarta.activation-api-1.2.1.jar:dependencies/jakarta.annotation.jakarta.annotation-api-1.3.5.jar:dependencies/jakarta.el.jakarta.el-api-3.0.3.jar:dependencies/jakarta.enterprise.jakarta.enterprise.cdi-api-2.0.2.jar:dependencies/jakarta.inject.jakarta.inject-api-1.0.jar:dependencies/jakarta.interceptor.jakarta.interceptor-api-1.2.5.jar:dependencies/jakarta.transaction.jakarta.transaction-api-1.3.3.jar:dependencies/joda-time.joda-time-2.9.9.jar:dependencies/org.apache.camel.camel-api-3.5.0.jar:dependencies/org.apache.camel.camel-aws-s3-3.5.0.jar:dependencies/org.apache.camel.camel-base-3.5.0.jar:dependencies/org.apache.camel.camel-bean-3.5.0.jar:dependencies/org.apache.camel.camel-componentdsl-3.5.0.jar:dependencies/org.apache.camel.camel-core-catalog-3.5.0.jar:dependencies/org.apache.camel.camel-core-engine-3.5.0.jar:dependencies/org.apache.camel.camel-core-languages-3.5.0.jar:dependencies/org.apache.camel.camel-direct-3.5.0.jar:dependencies/org.apache.camel.camel-endpointdsl-3.5.0.jar:dependencies/org.apache.camel.camel-jackson-3.5.0.jar:dependencies/org.apache.camel.camel-main-3.5.0.jar:dependencies/org.apache.camel.camel-management-api-3.5.0.jar:dependencies/org.apache.camel.camel-microprofile-config-3.5.0.jar:dependencies/org.apache.camel.camel-openapi-java-3.5.0.jar:dependencies/org.apache.camel.camel-platform-http-3.5.0.jar:dependencies/org.apache.camel.camel-rest-3.5.0.jar:dependencies/org.apache.camel.camel-support-3.5.0.jar:dependencies/org.apache.camel.camel-tooling-model-3.5.0.jar:dependencies/org.apache.camel.camel-util-3.5.0.jar:dependencies/org.apache.camel.camel-util-json-3.5.0.jar:dependencies/org.apache.camel.camel-xml-io-3.5.0.jar:dependencies/org.apache.camel.k.camel-k-loader-java-1.5.0.jar:dependencies/org.apache.camel.k.camel-k-loader-xml-1.5.0.jar:dependencies/org.apache.camel.k.camel-k-quarkus-core-1.5.0.jar:dependencies/org.apache.camel.k.camel-k-quarkus-loader-java-1.5.0.jar:dependencies/org.apache.camel.k.camel-k-quarkus-loader-xml-1.5.0.jar:dependencies/org.apache.camel.k.camel-k-runtime-core-1.5.0.jar:dependencies/org.apache.camel.k.camel-k-runtime-quarkus-1.5.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-aws-s3-1.1.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-bean-1.1.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-core-1.1.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-direct-1.1.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-endpointdsl-1.1.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-jackson-1.1.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-main-1.1.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-platform-http-1.1.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-rest-1.1.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-support-aws-1.1.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-support-common-1.1.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-support-commons-logging-1.1.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-support-xml-1.1.0.jar:dependencies/org.apache.camel.quarkus.camel-quarkus-xml-io-1.1.0.jar:dependencies/org.apache.httpcomponents.httpclient-4.5.12.jar:dependencies/org.apache.httpcomponents.httpcore-4.4.13.jar:dependencies/org.codehaus.woodstox.stax2-api-4.2.jar:dependencies/org.eclipse.microprofile.config.microprofile-config-api-1.4.jar:dependencies/org.eclipse.microprofile.context-propagation.microprofile-context-propagation-api-1.0.1.jar:dependencies/org.eclipse.microprofile.reactive-streams-operators.microprofile-reactive-streams-operators-api-1.0.1.jar:dependencies/org.eclipse.microprofile.reactive-streams-operators.microprofile-reactive-streams-operators-core-1.0.1.jar:dependencies/org.glassfish.jaxb.jaxb-runtime-2.3.3-b02.jar:dependencies/org.glassfish.jaxb.txw2-2.3.3-b02.jar:dependencies/org.graalvm.sdk.graal-sdk-20.2.0.jar:dependencies/org.jboss.logging.commons-logging-jboss-logging-1.0.0.Final.jar:dependencies/org.jboss.logging.jboss-logging-3.3.2.Final.jar:dependencies/org.jboss.logging.jboss-logging-annotations-2.1.0.Final.jar:dependencies/org.jboss.logmanager.jboss-logmanager-embedded-1.0.4.jar:dependencies/org.jboss.slf4j.slf4j-jboss-logging-1.2.0.Final.jar:dependencies/org.jboss.spec.javax.xml.bind.jboss-jaxb-api_2.3_spec-2.0.0.Final.jar:dependencies/org.jboss.threads.jboss-threads-3.1.1.Final.jar:dependencies/org.jooq.joor-0.9.13.jar:dependencies/org.mvel.mvel2-2.3.1.Final.jar:dependencies/org.reactivestreams.reactive-streams-1.0.3.jar:dependencies/org.slf4j.slf4j-api-1.7.30.jar:dependencies/org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar:dependencies/org.yaml.snakeyaml-1.26.jar:dependencies/software.amazon.ion.ion-java-1.0.2.jar io.quarkus.runner.GeneratedMain
[1] 2020-11-18 20:06:56,492 INFO  [org.apa.cam.k.Runtime] (main) Apache Camel K Runtime 1.5.0
[1] 2020-11-18 20:06:56,528 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
[1] 2020-11-18 20:06:56,655 INFO  [org.apa.cam.k.lis.SourcesConfigurer] (main) Loading routes from: SourceDefinition{name='MinioCustomizer', language='java', location='file:/etc/camel/sources/i-source-000/MinioCustomizer.java', }
[1] 2020-11-18 20:06:57,498 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: org.apache.camel.RuntimeCamelException: java.lang.ClassCastException: class test.MinioCustomizer cannot be cast to class org.apache.camel.RoutesBuilder (test.MinioCustomizer is in unnamed module of loader org.joor.Compile$ByteArrayClassLoader @1d61c6dc; org.apache.camel.RoutesBuilder is in unnamed module of loader 'app')
[1] 	at org.apache.camel.RuntimeCamelException.wrapRuntimeCamelException(RuntimeCamelException.java:51)
[1] 	at org.apache.camel.k.support.SourcesSupport.load(SourcesSupport.java:112)
[1] 	at org.apache.camel.k.support.SourcesSupport.loadSources(SourcesSupport.java:85)
[1] 	at org.apache.camel.k.listener.SourcesConfigurer.accept(SourcesConfigurer.java:73)
[1] 	at org.apache.camel.k.listener.AbstractPhaseListener.accept(AbstractPhaseListener.java:32)
[1] 	at org.apache.camel.k.quarkus.Application$ListenerAdapter.invokeListeners(Application.java:141)
[1] 	at org.apache.camel.k.quarkus.Application$ListenerAdapter.beforeConfigure(Application.java:103)
[1] 	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:651)
[1] 	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:97)
[1] 	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:67)
[1] 	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
[1] 	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:118)
[1] 	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
[1] 	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
[1] 	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
[1] 	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
[1] 	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:752)
[1] 	at io.quarkus.runtime.Application.start(Application.java:90)
[1] 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:91)
[1] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
[1] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
[1] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
[1] 	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
[1] Caused by: java.lang.ClassCastException: class test.MinioCustomizer cannot be cast to class org.apache.camel.RoutesBuilder (test.MinioCustomizer is in unnamed module of loader org.joor.Compile$ByteArrayClassLoader @1d61c6dc; org.apache.camel.RoutesBuilder is in unnamed module of loader 'app')
[1] 	at org.apache.camel.k.loader.java.JavaSourceLoader.load(JavaSourceLoader.java:51)
[1] 	at org.apache.camel.k.support.SourcesSupport.load(SourcesSupport.java:104)
[1] 	... 21 more
```

**Comment by hguerrero** [comment]
@weimeilin79 can you check this?

**Comment by weimeilin79** [comment]
@sobkowiak Can you verify and close if it's fixed.
